version: '2'
services:
  emergency-response-service:
    environment:
    - PROJ_SETTINGS_DIR=${PROJ_SETTINGS_DIR}
    - DEPLOY_TARGET=${DEPLOY_TARGET}
    build: .
    image: "${DOCKER_REPO}/${DOCKER_IMAGE}"
    command: /code/docker-entrypoint.sh
    volumes:
      - .:/code
    ports:
      - "8000:8000"
