version: '2'
services:
  emergency-service:
    environment:
    - PROJ_SETTINGS_DIR=${PROJ_SETTINGS_DIR}
    - DEPLOY_TARGET=${DEPLOY_TARGET}
    - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
    - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
    - CONFIG_BUCKET=${CONFIG_BUCKET}
    - DEBUG=False
    - NEWRELIC_LICENSE_KEY=${NEWRELIC_LICENSE_KEY}
    build: .
    image: "${DOCKER_REPO}/${DEPLOY_TARGET}/${DOCKER_IMAGE}:latest"
    command: ./code/bin/docker-entrypoint.sh
    volumes:
      - .:/code
    ports:
      - "8000:8000"


  # uncomment geocoder if using endpoint and add pword to env variables either in env.sh locally and/or in the travis build if deploying

  # geocoder-service:
  #     build: .
  #     environment:
  #         - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
  #     image: docker.io/znmeb/postgis:build
